"""Human-readable descriptions for each strategy family."""

DESCRIPTIONS = {
    "EmaCross": {
        "what": "Uses two Exponential Moving Averages — a fast one and a slow one. Buys when fast crosses above slow, sells when fast crosses back below.",
        "why_works": "EMAs react to recent prices more than old ones. When the fast line crosses the slow line, it's a clean signal that short-term momentum has flipped direction.",
        "pros": ["Simple, battle-tested", "Catches strong trends early", "Works well on trending assets like BTC/ETH"],
        "cons": ["Chops sideways markets into lots of losing trades", "Late to reversals by design"],
        "regime": "trend",
    },
    "RsiMeanReversion": {
        "what": "The Relative Strength Index measures how overbought or oversold something is on a 0–100 scale. Buys when RSI drops into oversold territory and sells when it climbs into overbought.",
        "why_works": "Markets overreact short-term. RSI catches the moments when price stretches too far and is due to snap back.",
        "pros": ["High win rate on range-bound assets", "Clear entry and exit signals"],
        "cons": ["Gets crushed in strong trends (keeps catching falling knives)", "Short holding periods → fees matter"],
        "regime": "mean-reversion",
    },
    "BollingerBreakout": {
        "what": "Bollinger Bands sit at ±N standard deviations above and below a moving average. This strategy buys when price breaks above the upper band.",
        "why_works": "A break above the upper band means volatility just expanded and price is accelerating — often the start of a move.",
        "pros": ["Catches the start of volatility surges", "Self-adjusts to each asset's typical range"],
        "cons": ["Gets faked out at local tops", "Stops can be wide in volatile markets"],
        "regime": "breakout",
    },
    "BollingerReversion": {
        "what": "Same Bollinger Bands, opposite philosophy: buys when price drops *below* the lower band, expecting a bounce back to the middle.",
        "why_works": "When price stretches to the lower band, it's statistically far from the mean. Often snaps back.",
        "pros": ["High hit rate in ranging markets", "Clear profit target (the middle band)"],
        "cons": ["Catches falling knives in downtrends", "Needs discipline with stops"],
        "regime": "mean-reversion",
    },
    "DonchianBreakout": {
        "what": "Buys when price hits a new N-bar high. This is the classic Turtle Traders rule from the 1980s.",
        "why_works": "New highs attract momentum buyers and trigger stops of shorts — reflexive fuel for the trend.",
        "pros": ["Captures long trends fully", "Simple and robust across assets"],
        "cons": ["Many false breakouts — low win rate, big winners compensate", "Painful drawdowns between trends"],
        "regime": "breakout",
    },
    "MacdMomentum": {
        "what": "MACD = difference between a fast EMA and a slow EMA, with a signal line. Trades when MACD crosses the signal line, with an extra 'above zero' filter for direction.",
        "why_works": "Combines trend direction with momentum acceleration — a two-factor confirmation.",
        "pros": ["Filters out weak crossovers", "Popular = reflexive moves"],
        "cons": ["Lags", "Requires a strong trend to deliver"],
        "regime": "trend",
    },
    "KeltnerBreakout": {
        "what": "Like Bollinger but uses Average True Range instead of standard deviation. Buys breakouts above the upper channel.",
        "why_works": "ATR adapts to each asset's volatility, so thresholds stay meaningful across high- and low-vol coins.",
        "pros": ["Adapts channel to actual volatility", "Fewer false breakouts than Bollinger"],
        "cons": ["Still whipsaws in chop", "Late exits"],
        "regime": "breakout",
    },
    "Supertrend": {
        "what": "ATR-based trailing-stop indicator. Flips from 'down' to 'up' when price crosses a dynamically calculated line. Buys on flip-up.",
        "why_works": "Visual and mechanical. Built-in trailing stop means you ride trends and exit cleanly.",
        "pros": ["Automatic trailing stops", "Easy to read on charts"],
        "cons": ["Frequent flips in sideways markets", "ATR lag"],
        "regime": "trend",
    },
    "MomentumRoc": {
        "what": "Rate-of-Change: what percent has price moved in the last N bars? Buys when ROC crosses a threshold.",
        "why_works": "Pure momentum — recent winners keep winning, short-term.",
        "pros": ["Catches explosive moves", "Pure signal, no lag"],
        "cons": ["Often buys the top of spikes", "Needs quick exits to survive reversals"],
        "regime": "momentum",
    },
    "VwapReversion": {
        "what": "Volume-Weighted Average Price is the 'fair' price accounting for volume. Buys when price falls way below VWAP, targeting reversion to it.",
        "why_works": "Institutions anchor around VWAP. Extreme deviations often get arbed away.",
        "pros": ["Solid intraday edge", "Institutional anchor = real pull"],
        "cons": ["VWAP loses meaning in choppy low-volume sessions", "Doesn't catch breakout moves"],
        "regime": "mean-reversion",
    },
    "Ichimoku": {
        "what": "A multi-line Japanese system: two trigger lines (Tenkan/Kijun), a 'cloud' (Kumo) of future support/resistance, and a lagging span. Buys when the faster line crosses above the slower one — above the cloud.",
        "why_works": "Combines multiple timeframes into one chart. The cloud-position filter avoids counter-trend trades.",
        "pros": ["Built-in trend filter", "Strong signals when all pieces align"],
        "cons": ["Complex", "Signals are rare → fewer trades"],
        "regime": "trend",
    },
    "Stochastic": {
        "what": "Compares current price to its N-bar range. Oscillates 0–100. Buys on bounce out of oversold (<20).",
        "why_works": "Picks turning points within a range. Works well on sideways assets.",
        "pros": ["High resolution for timing", "Clear overbought/oversold extremes"],
        "cons": ["Stays 'overbought' all through strong trends", "Needs trend filter to be safe"],
        "regime": "mean-reversion",
    },
    "WilliamsR": {
        "what": "Essentially an inverted Stochastic. Values from -100 (oversold) to 0 (overbought). Buys when it dips below -80.",
        "why_works": "Detects short-term exhaustion. Fast, reactive.",
        "pros": ["Very responsive", "Simple to read"],
        "cons": ["Whipsaws in trending markets", "Noisy without a filter"],
        "regime": "mean-reversion",
    },
    "CCI": {
        "what": "Commodity Channel Index — measures how far price is from its average, in units of mean deviation. Buys when it climbs back from extreme negative readings.",
        "why_works": "Catches the moment an oversold move stops getting more oversold — the reversal hinge.",
        "pros": ["Sensitive to turning points", "Works on many asset classes"],
        "cons": ["Fires too often without filters", "Can stay extreme for a while"],
        "regime": "mean-reversion",
    },
    "AdxTrend": {
        "what": "EMA crossover — but only takes the trade if ADX (trend strength) is above a threshold, so it skips choppy markets.",
        "why_works": "The biggest killer of trend systems is sideways chop. ADX filter sidesteps that.",
        "pros": ["Avoids the worst chop losses", "Better win rate than raw EMA cross"],
        "cons": ["Misses early trends (ADX is lagging)", "Fewer trades"],
        "regime": "trend",
    },
    "Aroon": {
        "what": "Measures how many bars since the last N-bar high vs low. Buys when the Up line surges and Down line collapses.",
        "why_works": "Cleanly identifies fresh trend formation, not old noise.",
        "pros": ["Catches trend starts", "Intuitive"],
        "cons": ["Lags in brand-new assets", "Weak in sideways markets"],
        "regime": "trend",
    },
    "ParabolicSar": {
        "what": "Prints dots above/below price that follow the trend with acceleration. Flip side = trend change. Buys on flip-to-below-price.",
        "why_works": "Built-in trailing stop that accelerates with trend strength.",
        "pros": ["Tight trailing stops", "No indicator math to fight"],
        "cons": ["Flips constantly in chop", "Exits trends too early"],
        "regime": "trend",
    },
    "HullMaCross": {
        "what": "Hull Moving Average is a smoother, faster MA variant. Trades Hull MA crossovers.",
        "why_works": "Lower lag than EMAs — earlier signals with less noise.",
        "pros": ["Fast response", "Smooth (less noise)"],
        "cons": ["Still lags in violent moves", "Some whipsaw"],
        "regime": "trend",
    },
    "TemaCross": {
        "what": "Triple-EMA cross — uses a formula that subtracts EMA lag aggressively. Even faster than Hull.",
        "why_works": "Minimizes the time between a real turn in price and the signal.",
        "pros": ["Very fast signals", "Works in fast assets"],
        "cons": ["Noisy in calm markets", "Can fire on small wiggles"],
        "regime": "trend",
    },
    "FisherTransform": {
        "what": "Ehlers' math transform that forces normally-distributed price into a bounded range, making extremes stand out.",
        "why_works": "Highlights real reversals vs normal noise via Gaussian normalization.",
        "pros": ["Sharp, clear turning-point signals", "Academic backing"],
        "cons": ["Complex to reason about", "Requires calm to work well"],
        "regime": "mean-reversion",
    },
    "KaufmanAdaptiveMa": {
        "what": "Moving average whose smoothing speeds up in trends and slows down in chop automatically.",
        "why_works": "Adapts to market conditions — fast when needed, slow when noisy.",
        "pros": ["Self-tuning", "Less whipsaw than fixed MAs"],
        "cons": ["Still an MA — inherently lagging", "Params need tuning"],
        "regime": "trend",
    },
    "HeikinAshiTrend": {
        "what": "Uses smoothed candles that filter out noise. Buys after N consecutive green candles.",
        "why_works": "The smoothing filters out false reversals — only real trends keep the candles one color.",
        "pros": ["Cuts false signals", "Very visual"],
        "cons": ["Late entries", "Late exits"],
        "regime": "trend",
    },
    "ZScoreMR": {
        "what": "Rolling z-score of price: how many standard deviations below the N-bar mean are we? Buys when cheap, sells near mean.",
        "why_works": "Pure statistical mean-reversion — works whenever returns are stationary.",
        "pros": ["Rigorous math foundation", "Clean entry/exit rules"],
        "cons": ["Deadly in regime changes", "Needs tight stops"],
        "regime": "mean-reversion",
    },
    "ChandeMomentum": {
        "what": "Like RSI but uses raw up/down sums differently. Ranges -100 to +100. Buys crossing out of -50.",
        "why_works": "More symmetric than RSI, catches momentum shifts cleanly.",
        "pros": ["Symmetric signal", "Good on oscillating assets"],
        "cons": ["Less known = less reflexive edge", "Noisy at extremes"],
        "regime": "momentum",
    },
    "ObvDivergence": {
        "what": "On-Balance Volume tracks cumulative volume direction. This variant buys when OBV and price both break to new highs.",
        "why_works": "Volume leads price. New OBV highs mean real buying pressure is behind the move.",
        "pros": ["Volume confirmation = less fake-outs", "Works on stocks and crypto"],
        "cons": ["Needs quality volume data (thin markets = noise)", "Requires discipline on stops"],
        "regime": "breakout",
    },
}


def get(class_name: str) -> dict:
    return DESCRIPTIONS.get(class_name, {
        "what": "No description yet.", "why_works": "—",
        "pros": [], "cons": [], "regime": "unknown",
    })
